# Site settings
name: Lalitha Krishnan Menon
email: lalithamenon92@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Swift, AI, Java, iOS, Android, Agile, Python "
skills: "Senior Systems Engineer"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/lalitha-menon-33748613a
 # - title: medium
  #  url: https://medium.com/@cgroom
  #- title: twitter
   # url: https://twitter.com/chuck_groom
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d19259    
  primary-rgb: "33, 150, 243"
  secondary: 424949
  secondary-dark: 424949
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
